server:
  port: 8080

spring:
  application:
    name: task_management_system
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/task_management_system?useSSL=false
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  aop:
    auto: true
    proxy-target-class: true
#logging:
#  level:
#    org:
#      hibernate:
#        sql: debug
#        type:
#          descriptor:
#            sql: trace
